package tcp.trab_1.parse;

public enum Action {
    PLAY_A,
    PLAY_B,
    PLAY_C,
    PLAY_D,
    PLAY_E,
    PLAY_F,
    PLAY_G,

    PAUSE,

    DOUBLE_VOLUME_ROLL_OVER,
    OCTAVE_UP_ROLL_OVER,

    CHANGE_INSTRUMENT_TO_GENERAL_MIDI_114,
    CHANGE_INSTRUMENT_TO_GENERAL_MIDI_7,
    CHANGE_INSTRUMENT_TO_GENERAL_MIDI_15,
    CHANGE_INSTRUMENT_TO_GENERAL_MIDI_76,
    CHANGE_INSTRUMENT_TO_GENERAL_MIDI_20,

    INCREASE_INSTRUMENT_BY_0,
    INCREASE_INSTRUMENT_BY_1,
    INCREASE_INSTRUMENT_BY_2,
    INCREASE_INSTRUMENT_BY_3,
    INCREASE_INSTRUMENT_BY_4,
    INCREASE_INSTRUMENT_BY_5,
    INCREASE_INSTRUMENT_BY_6,
    INCREASE_INSTRUMENT_BY_7,
    INCREASE_INSTRUMENT_BY_8,
    INCREASE_INSTRUMENT_BY_9
}
